[2023-11-23T17:50:32.562+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task scheduled__2023-11-23T05:00:00+00:00 [queued]>
[2023-11-23T17:50:32.591+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task scheduled__2023-11-23T05:00:00+00:00 [queued]>
[2023-11-23T17:50:32.591+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-11-23T17:50:32.663+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): load_to_bq_task> on 2023-11-23 05:00:00+00:00
[2023-11-23T17:50:32.671+0000] {standard_task_runner.py:57} INFO - Started process 453534 to run task
[2023-11-23T17:50:32.678+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_SFCrimes_data_bqload', 'load_to_bq_task', 'scheduled__2023-11-23T05:00:00+00:00', '--job-id', '647', '--raw', '--subdir', 'DAGS_FOLDER/curated/dag_sf_crimes_bqload.py', '--cfg-path', '/tmp/tmpq4f1kd44']
[2023-11-23T17:50:32.682+0000] {standard_task_runner.py:85} INFO - Job 647: Subtask load_to_bq_task
[2023-11-23T17:50:32.833+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task scheduled__2023-11-23T05:00:00+00:00 [running]> on host jarvis
[2023-11-23T17:50:33.371+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_SFCrimes_data_bqload' AIRFLOW_CTX_TASK_ID='load_to_bq_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-23T05:00:00+00:00'
[2023-11-23T17:50:34.816+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mani-dev/airflow/dags/curated/dag_sf_crimes_bqload.py", line 33, in load_bq_raw
    with open(source_file, "rb") as source_file:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/ssd/external/projects/sf_crimes/SFcrimes_2023112317.csv'
[2023-11-23T17:50:34.850+0000] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_SFCrimes_data_bqload, task_id=load_to_bq_task, execution_date=20231123T050000, start_date=20231123T175032, end_date=20231123T175034
[2023-11-23T17:50:34.936+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 647 for task load_to_bq_task ([Errno 2] No such file or directory: '/mnt/ssd/external/projects/sf_crimes/SFcrimes_2023112317.csv'; 453534)
[2023-11-23T17:50:34.984+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-11-23T17:50:35.066+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-11-23T19:30:10.331+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task scheduled__2023-11-23T05:00:00+00:00 [queued]>
[2023-11-23T19:30:10.378+0000] {taskinstance.py:1125} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task scheduled__2023-11-23T05:00:00+00:00 [queued]>
[2023-11-23T19:30:10.379+0000] {taskinstance.py:1331} INFO - Starting attempt 1 of 2
[2023-11-23T19:30:10.449+0000] {taskinstance.py:1350} INFO - Executing <Task(PythonOperator): load_to_bq_task> on 2023-11-23 05:00:00+00:00
[2023-11-23T19:30:10.469+0000] {standard_task_runner.py:57} INFO - Started process 465889 to run task
[2023-11-23T19:30:10.481+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'dag_SFCrimes_data_bqload', 'load_to_bq_task', 'scheduled__2023-11-23T05:00:00+00:00', '--job-id', '680', '--raw', '--subdir', 'DAGS_FOLDER/curated/dag_sf_crimes_bqload.py', '--cfg-path', '/tmp/tmp37qnm668']
[2023-11-23T19:30:10.487+0000] {standard_task_runner.py:85} INFO - Job 680: Subtask load_to_bq_task
[2023-11-23T19:30:10.809+0000] {task_command.py:410} INFO - Running <TaskInstance: dag_SFCrimes_data_bqload.load_to_bq_task scheduled__2023-11-23T05:00:00+00:00 [running]> on host jarvis
[2023-11-23T19:30:11.336+0000] {taskinstance.py:1568} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='dag_SFCrimes_data_bqload' AIRFLOW_CTX_TASK_ID='load_to_bq_task' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T05:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-23T05:00:00+00:00'
[2023-11-23T19:30:13.136+0000] {taskinstance.py:1847} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/mani-dev/airflow/dags/curated/dag_sf_crimes_bqload.py", line 32, in load_bq_raw
    with open(source_file, "rb") as source_file:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/ssd/external/projects/sf_crimes/SFcrimes_2023112319.csv'
[2023-11-23T19:30:13.172+0000] {taskinstance.py:1368} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_SFCrimes_data_bqload, task_id=load_to_bq_task, execution_date=20231123T050000, start_date=20231123T193010, end_date=20231123T193013
[2023-11-23T19:30:13.236+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 680 for task load_to_bq_task ([Errno 2] No such file or directory: '/mnt/ssd/external/projects/sf_crimes/SFcrimes_2023112319.csv'; 465889)
[2023-11-23T19:30:13.282+0000] {local_task_job_runner.py:232} INFO - Task exited with return code 1
[2023-11-23T19:30:13.340+0000] {taskinstance.py:2674} INFO - 0 downstream tasks scheduled from follow-on schedule check
